const asyncHandler = (requestHandler) => {
  return (req, res, next) => {
    Promise.resolve(requestHandler(req, res, next)).catch((error) =>
      next(error)
    );
  };
};
export { asyncHandler };

// we can do in this method using try catch

// const asyncHandler = () => {};
// const asyncHandler = (func) =>
//   () => {};
// ;
// const asyncHandler = (func) =>
//  async () => {};
// ;
// const asyncHandler = (fn) => async (req, res, next) => {
//   try {
//     await fn(req, res, next);
//   } catch (error) {
//     res.status(error.code || 500).json({
//       success: false,
//       message: error.message,
//     });
//   }
// };
